### ISSUE TITLE
Modify tasks that are not work orders

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/react-maintenance-planner#55]
Blue tasks on 2nd level are not work orders. Therefore, color should be different and specified in legend.

![image](https://user-images.githubusercontent.com/57750426/179184365-3d548e59-0359-4a40-81ed-5967941d1bff.png)

**Comment by LaChope** [comment]
@kalamartin 

We need to define colors and names for different types of boxes in the diagram, each box is in different resource group. This is current assignment of resource groups

1. Whole aircraft  -- Phases (blue)
2. Area  -- What should be the name (propose color)?
3. Group of people (resources) -- Schedules WO (red) - Maintenance WO (blue) - Task cards (green) ?
4. Concrete person/mechanic -- Work session (yellow)

Please, can you check terminology, suggest colors / better names if needed so.
If not clear, please comment.

**Comment by kalamartin** [comment]
1) Phases can stay blue. Eg Phase 1, phase 2....
2) Boxes which  have been considered as workorders but actually are "Taskcard type groups" can be with turquoise.
3) Areas are just areas, not needed to define more I guess. There are on the very left side and can be marked as you wanted by colour.
4) Resources ...ussually in excel sheet workplan, each scope has its own colour, so as the tasks in the workplan. Since each task (WO M, WO S and especially taskcards) belongs to specifics scope, it could be done as like that. Please advis if possible.
Therefore color for TC, WO M and S wouldn´t be needed.

I guess rest is ok.

**Comment by LaChope** [comment]
Here are the updated colors along with the legend. @kalamartin can you check if legend is correct and if colors are ok? 
I  left tasks cards in green and made WO M, WO S some gradient of green. 

If you have any suggestion / comment let me know @kalamartin @blcham

![image](https://user-images.githubusercontent.com/57750426/194020450-81164f3b-2ed3-4ae1-ad29-37039fca3e80.png)
![image](https://user-images.githubusercontent.com/57750426/194020809-d69a3c3e-74c0-49f6-8d9c-be964acbe6c6.png)

**Comment by kalamartin** [comment]
I would suggest Maintenance WO´s to be RED. The yellow color is easily to swap with Scheduled WO. Otherwise ok.

@LaChope

**Comment by LaChope** [comment]
Ok, thanks for feedback. Here is the new version:

![image](https://user-images.githubusercontent.com/57750426/194030008-0617ddf9-12a3-4c10-acaf-468ff8ec214a.png)
